---
- name: Find /var/lib/phoronix-test-suite/test-results/ all directories
  find:
    paths: /var/lib/phoronix-test-suite/test-results
    recurse: no
    file_type: directory
  register: dir_list
#- debug: var=dir_list

- name: /var/lib/phoronix-test-suite/test-results/*/composite.xml to {{ ansible_host }} {{ item.path|basename }}
  xml:
    path: '{{ item.path }}/composite.xml'
    xpath: /PhoronixTestSuite/System/Identifier
    value: '{{ ansible_hostname }} {{ ansible_fqdn }} {{ item.path|basename }}'
  loop: '{{ dir_list.files }}'
#- name: test 2
#  xml:
#    path: /var/lib/phoronix-test-suite/test-results/{{ item.value }}/composite.xml
#    xpath: /PhoronixTestSuite/Result/Data/Entry/Identifier
#    value: '{{ ansible_host }} {{ item.value }}'
#  loop: {{ lookup('dict', dir_list|default()) }}
